### ISSUE TITLE
BUG: Extension breaks UI restarting

### ISSUE THREAD

**Issue by MIC132** [chrisgoringe/Styles-Editor#58] opened 2023-06-25 17:53 UTC
I though I was going crazy, but I managed to pinpoint my issue to this extension.

Whenever I have this extension enabled, doing any UI restart (be it from settings -> restart UI, or extensions -> Apply and Restart UI) it just doesn't work. The console output stops at "Restarting UI..." and never gets to "Closing server running on port: (...)".
If I have this extension disabled, everything is ok.

When enabling/disabling the extension itself, it works like that:
Extension currently disabled -> check it -> Apply and restart UI -> will work
Extension currently enabled (for example after the above) -> uncheck it -> Apply and restart UI -> will get stuck
You have to restart the whole terminal for it to work (and the extension will then be properly disabled)

I hope this can be fixed, since I really like the extension otherwise.

**Comment by chrisgoringe** [comment] 2023-06-26 02:34
Caused by the background task that does backups. Looks like using the 'every' parameter of a gradio task stops the interface from closing (maybe only when it has no inputs or outputs?).

So change the backup to use its own (daemon) thread,

Fixed in latest commit.

**Closed by chrisgoringe** 2023-06-26 02:34 UTC
