### ISSUE TITLE
Styles being deleted :(

### ISSUE THREAD

**Issue by futuranewworld** [chrisgoringe/Styles-Editor#83] opened 2023-07-06 01:55 UTC
After creating a new style in automatic1111, I navigated to the style editor tab and observed the refresh animation.

I then checked for the new style in the style editor tab and it seemed like it auto deleted it. Did the experiment again but this time I checked the styles csv file to make sure the new style was added in the first place (and it was). But every time I navigate to the style editor tab, it deletes all new styles and resets to default.

Any tips on what I am doing wrong perhaps?

**Comment by chrisgoringe** [comment] 2023-07-06 02:35
I believe this is fixed now. Perhaps you can check.

**Comment by chrisgoringe** [comment] 2023-07-06 02:37
Implementation note - the styles are cached by the Styles Editor. When new styles are added through the other parts of the UI, they aren't in the cache. 

Solution is to drop the cache when moving to and from the Styles Editor tab.

**Comment by futuranewworld** [comment] 2023-07-06 12:50
It is fixed now! thanks for all you do!

**Comment by futuranewworld** [comment] 2023-07-07 11:46
Issue seemed to persist this morning.

After I changed runtime to another GPU and booted up automatic1111, I navigated to style editor and all styles were deleted. Not only newly added styles but also styles that were made several months ago. I wish I could provide more details but all of this happened after a simple runtime switch.

**Comment by chrisgoringe** [comment] 2023-07-07 13:24
Could you let me know which commit that happened with? Obviously a high priority to get to the bottom of this.

(Also, there should be a backups folder, hopefully containing some csv files you can restore from.)

**Comment by chrisgoringe** [comment] 2023-07-07 13:26
Another question - do you use the additional style files feature? Knowing that would help me Marie's down the search.

**Comment by futuranewworld** [comment] 2023-07-07 14:20
> It is fixed now! thanks for all you do!

I updated my Style Editor right before I made this comment so it must have been this version. Since the issue occurred I have restarted and reinstalled different things many times.



> Another question - do you use the additional style files feature? Knowing that would help me Marie's down the search.

I do not.

**Comment by chrisgoringe** [comment] 2023-07-08 00:16
Thanks. 

I can't reproduce this on the latest build - [7ed19fc8](https://github.com/chrisgoringe/Styles-Editor/commit/7ed19fc8e8931991dd49c2941208232c109e6829) - so I'm at something of a loss. Could I ask you to see if it reoccurs and give me any details you can if it does?

I'll leave this open for a while; if it doesn't reoccur I might close it, but won't lock it, so you can always add comments and I'll see them.

I hope that the backups meant you didn't lose your saved styles... maybe make a manual backup as well just in case until I get to the bottom of this.

(Oh, and "help me Marie's down the search"? Seriously, autocorrect, was that the best you could come up with?)

**Comment by chrisgoringe** [comment] 2023-07-13 16:47
Just checking if the problem has recurred before I close this issue...

**Comment by futuranewworld** [comment] 2023-07-14 22:04
Sorry for late reply. After the problem occurred I reinstalled everything including A1111 to the latest version and the problem cannot be produced. Not sure what caused it to be completely honest. I will add comments if it resurfaces for sure.

**Closed** 2023-07-15 10:21 UTC
